dev/protected/models/Evento.php
<?php

/**
 * This is the model class for table "noticia".
 *
 * The followings are the available columns in table 'noticia':
 * @property integer $id
 * @property string $titulo_pt
 * @property string $titulo_en
 * @property string $titulo_fr
 * @property string $titulo_es
 * @property string $conteudo_pt
 * @property string $conteudo_en
 * @property string $conteudo_fr
 * @property string $conteudo_es
 * @property string $data
 * @property string $imagem
 */
class Evento extends CActiveRecord
{
	/**
	 * Returns the static model of the specified AR class.
	 * @param string $className active record class name.
	 * @return Noticia the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}
       
        
	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'noticia';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('titulo_pt, conteudo_pt, data, data_fim', 'required'),
			array('titulo_pt, titulo_en, titulo_fr, titulo_es', 'length', 'max'=>100),
			array('imagem', 'length', 'max'=>45),
			array('conteudo_en, conteudo_fr, conteudo_es, link, imagem', 'safe'),
			// The following rule is used by search().
			// Please remove those attributes that should not be searched.
			array('id, titulo_pt, titulo_en, titulo_fr, titulo_es, conteudo_pt, conteudo_en, conteudo_fr, conteudo_es, data, imagem', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'titulo_pt' => 'Título PT',
			'titulo_en' => 'Título EN',
			'titulo_fr' => 'Título FR',
			'titulo_es' => 'Título ES',
			'conteudo_pt' => 'Conteúdo PT',
			'conteudo_en' => 'Conteúdo EN',
			'conteudo_fr' => 'Conteúdo FR',
			'conteudo_es' => 'Conteúdo ES',
			'data' => 'Data Início',
                        'data_fim' => 'Data Fim',
			'imagem' => 'Imagem',
                        'link' => 'Link',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
	 */
	public function search()
	{
		// Warning: Please modify the following code to remove attributes that
		// should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id);
		$criteria->compare('titulo_pt',$this->titulo_pt,true);
		$criteria->compare('titulo_en',$this->titulo_en,true);
		$criteria->compare('titulo_fr',$this->titulo_fr,true);
		$criteria->compare('titulo_es',$this->titulo_es,true);
		$criteria->compare('conteudo_pt',$this->conteudo_pt,true);
		$criteria->compare('conteudo_en',$this->conteudo_en,true);
		$criteria->compare('conteudo_fr',$this->conteudo_fr,true);
		$criteria->compare('conteudo_es',$this->conteudo_es,true);
		$criteria->compare('data',$this->data,true);
                $criteria->compare('data_fim',$this->data_fim,true);
		$criteria->compare('imagem',$this->imagem,true);
                $criteria->compare('link',$this->imagem,true);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}
        
        public function createThumbnails($folder,$fileName){
            $cropper=new ImageCropper;
                                   
            $original_image_path=$folder. $fileName;
            list($width, $height) = getimagesize($original_image_path);
            
            $altura=($height*300)/$width;
            
            $dist_image_path=$folder.$fileName;
            $cropper->resize_and_crop($original_image_path, $dist_image_path, 300, $altura, 100 );
            
            //$dist_image_path=$folder."th_".$fileName;
            //$cropper->resize_and_crop($original_image_path, $dist_image_path, 70, 70, 100 );
            
            //$altura=($height*594)/$width;
            
            //$dist_image_path=$folder."fix_".$fileName;
            //$cropper->resize_and_crop($original_image_path, $dist_image_path, 594, $height, 100 );
           
        }
}

dev/protected/controllers/EventoController.php
<?php

class EventoController extends Controller
{
/**
* @var string the default layout for the views. Defaults to '//layouts/column2', meaning
* using two-column layout. See 'protected/views/layouts/column2.php'.
*/
public $layout='//layouts/column2';

/**
* @return array action filters
*/
public function filters()
{
return array(
'accessControl', // perform access control for CRUD operations
);
}

/**
* Specifies the access control rules.
* This method is used by the 'accessControl' filter.
* @return array access control rules
*/


public function accessRules()
{
return array(
array('allow',  // allow all users to perform 'index' and 'view' actions
'actions'=>array('index','view'),
'users'=>array('*'),
),
array('allow', // allow admin user to perform 'admin' and 'delete' actions
'actions'=>array('admin','delete','create','update','updateajax'),
'roles'=>array('admin'),
),
array('deny',  // deny all users
'users'=>array('*'),
),
);
}

/**
* Displays a particular model.
* @param integer $id the ID of the model to be displayed
*/
public function actionView($id)
{
$this->layout='//layouts/column1';    
    
$this->render('view',array(
'model'=>$this->loadModel($id),
));
}

/**
* Creates a new model.
* If creation is successful, the browser will be redirected to the 'view' page.
*/
public function actionCreate()
{
$model=new Evento;

// Uncomment the following line if AJAX validation is needed
// $this->performAjaxValidation($model);

if(isset($_POST['Evento']))
{
$model->attributes=$_POST['Evento'];


$rnd = md5(time());

$uploadedFile=CUploadedFile::getInstance($model,'imagem');

if(!empty($uploadedFile))
{
    $fileName = "{$rnd}.{$uploadedFile->extensionName}";
    $model->imagem = $fileName;
}

if($model->save()){
    if(!empty($uploadedFile)){
        $uploadedFile->saveAs(Yii::getPathOfAlias('webroot').'/uploads/'.$fileName);
        //if($uploadedFile->extensionName!="gif" && $uploadedFile->extensionName!="GIF")
          //  Evento::model()->createThumbnails(Yii::getPathOfAlias('webroot').'/uploads/',$fileName);
    }
    $this->redirect(array('admin'));
}


}

$this->render('create',array(
'model'=>$model,
));
}

/**
* Updates a particular model.
* If update is successful, the browser will be redirected to the 'view' page.
* @param integer $id the ID of the model to be updated
*/
public function actionUpdate($id)
{
$model=$this->loadModel($id);
$imagem_antiga=$model->imagem;
// Uncomment the following line if AJAX validation is needed
// $this->performAjaxValidation($model);

if(isset($_POST['Evento']))
{
$model->attributes=$_POST['Evento'];

    $rnd = md5(time());
    $model->attributes=$_POST['Evento'];
    $uploadedFile=CUploadedFile::getInstance($model,'imagem');
    if(!empty($uploadedFile))
        {
            $fileName = "{$rnd}.{$uploadedFile->extensionName}";
            $model->imagem = $fileName;
            
            $old_file=Evento::model()->findByPk($id)->imagem;
            if ($old_file!="" && $old_file!=null && file_exists(Yii::getPathOfAlias('webroot').'/uploads/'. $old_file))
            {
                unlink(Yii::getPathOfAlias('webroot').'/uploads/'. $old_file);
            }
        }
     elseif($imagem_antiga!="" && $imagem_antiga!=null)
         $model->imagem=$imagem_antiga;

if($model->save())
{
    if(!empty($uploadedFile))  
    {
        $uploadedFile->saveAs(Yii::app()->basePath.'/../uploads/'.$model->imagem);
        //if($uploadedFile->extensionName!="gif" && $uploadedFile->extensionName!="GIF")
          //  Evento::model()->createThumbnails(Yii::getPathOfAlias('webroot').'/uploads/',$fileName);
    }
    $this->redirect(array('admin'));
}
}

$this->render('update',array(
'model'=>$model,
));
}

/**
* Deletes a particular model.
* If deletion is successful, the browser will be redirected to the 'admin' page.
* @param integer $id the ID of the model to be deleted
*/
public function actionDelete($id)
{
if(Yii::app()->request->isPostRequest)
{
 
$old_file=Evento::model()->findByPk($id)->imagem;
if ($old_file!="" && $old_file!=null && file_exists(Yii::getPathOfAlias('webroot').'/uploads/'. $old_file))
    unlink(Yii::getPathOfAlias('webroot').'/uploads/'. $old_file);   

    
$old_file=Evento::model()->findByPk($id)->imagem;
if ($old_file!="" && $old_file!=null && file_exists(Yii::getPathOfAlias('webroot').'/uploads/'. $old_file))
{
    unlink(Yii::getPathOfAlias('webroot').'/uploads/'. $old_file);      
    //unlink(Yii::getPathOfAlias('webroot').'/uploads/'. "th_".$old_file);
    //unlink(Yii::getPathOfAlias('webroot').'/uploads/'. "fix_".$old_file);
}
    
// we only allow deletion via POST request
$this->loadModel($id)->delete();

// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
if(!isset($_GET['ajax']))
$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
}
else
throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
}

/**
* Lists all models.
*/
public function actionIndex()
{
$this->layout='//layouts/column1';

$dataProvider=new CActiveDataProvider('Evento',array(
            'criteria' => array(
                'order' => 'data DESC',
            ),
           // 'pagination' => array('pageSize' => 3,),
           // 'totalItemCount' => 3,
        ));
$this->render('index',array(
'dataProvider'=>$dataProvider,
));
}

/**
* Manages all models.
*/
public function actionAdmin()
{
$model=new Evento('search');
$model->unsetAttributes();  // clear any default values
if(isset($_GET['Evento']))
$model->attributes=$_GET['Evento'];

$this->render('admin',array(
'model'=>$model,
));
}

/**
* Returns the data model based on the primary key given in the GET variable.
* If the data model is not found, an HTTP exception will be raised.
* @param integer the ID of the model to be loaded
*/
public function loadModel($id)
{
$model=Evento::model()->findByPk($id);
if($model===null)
throw new CHttpException(404,'The requested page does not exist.');
return $model;
}

/**
* Performs the AJAX validation.
* @param CModel the model to be validated
*/
protected function performAjaxValidation($model)
{
if(isset($_POST['ajax']) && $_POST['ajax']==='evento-form')
{
echo CActiveForm::validate($model);
Yii::app()->end();
}
}

public function actionUpdateAjax($id)
        {
            
            $model=Evento::model()->findByPk($id);
            $fileName=$model->imagem;
            $model->imagem="";
            $model->save(false);
            if (file_exists(Yii::getPathOfAlias('webroot').'/uploads/'. $fileName))
                unlink(Yii::getPathOfAlias('webroot').'/uploads/'. $fileName);
           
            $this->renderPartial('_imagemContent', array('model'=>$model));
        }   

}

dev/protected/views/evento/_all_news.php
<?php
$titulo="titulo_".Yii::app()->language;
$criteria = new CDbCriteria(array('order'=>'data DESC'));
$news = Noticia::model()->findAllByAttributes(array(),$criteria);
if(sizeof($news)>=1)
{
    echo'<aside class="col-sm-3 sidebar">
                        <h3 class="article-title" >'.Content::model()->getContentReturn('outras-noticias',Yii::app()->language).'</h3>
                        <span class="line" >
                            <span class="sub-line" ></span>
                        </span>';
    echo'<ul class="custom-icon-list categories" >';
    foreach ($news as $n)
    {
        echo'<li><i class="entypo-cd" ></i>';
        echo CHtml::link($n->$titulo,array('view','id'=>$n->id));
        echo'</li>';
    }
    echo'</ul></aside>';
}
?>

dev/protected/views/evento/_form.php
<script src="<?php echo Yii::app()->baseUrl.'/ckeditor/ckeditor.js'; ?>"></script>
<?php $form=$this->beginWidget('bootstrap.widgets.TbActiveForm',array(
	'id'=>'evento-form',
	'enableAjaxValidation'=>false,
        'htmlOptions' => array(
            'enctype' => 'multipart/form-data',
        ),
)); ?>

<p class="help-block">Os campos com <span class="required">*</span> são obrigatórios.</p>

<?php echo $form->errorSummary($model); ?>

	<?php echo $form->textFieldRow($model,'titulo_pt',array('class'=>'span8','maxlength'=>100)); ?>

	<?php echo $form->textFieldRow($model,'titulo_es',array('class'=>'span8','maxlength'=>100)); ?>

        <?php echo $form->textFieldRow($model,'link',array('class'=>'span12','maxlength'=>100)); ?>

        <div class='control-group'>
        <?php echo $form->labelEx($model,'conteudo_pt',array('class'=>'control-label')); ?>   
        <div class='controls'>
        <?php
        echo $form->textArea($model, 'conteudo_pt', array('class'=>'span12', 'rows' => 6,'id'=>'some-textarea-pt','placeholder'=>''));
      
        ?>
        </div></div>
        <script type="text/javascript">
            CKEDITOR.replace( 'some-textarea-pt' );
        </script>
        
        
        <div class='control-group'>
        <?php echo $form->labelEx($model,'conteudo_es',array('class'=>'control-label')); ?>   
        <div class='controls'>
        <?php echo $form->textArea($model, 'conteudo_es', array('class'=>'span12', 'rows' => 6,'id'=>'some-textarea-es','placeholder'=>'')); ?>
        </div></div>
        <script type="text/javascript">
            CKEDITOR.replace( 'some-textarea-es' );
        </script>


        <div class='control-group'>
        <?php echo $form->labelEx($model,'data',array('class'=>'control-label')); ?>   
        <div class='controls'>   
         <?php 
         
         echo"<div class='input-prepend'><span class='add-on'><i class='icon-calendar'></i></span>";
         $this->widget('zii.widgets.jui.CJuiDatePicker', array(
                        'model'=>$model,
                        'attribute'=>'data',
                        'value'=>$model->data, 
                        'options'=>array(
                        'dateFormat' => 'yy-mm-dd',
                        'altFormat' => 'yy-mm-dd', // show to user format    
                        'showAnim'=>'fold',
                        ),
                        'htmlOptions'=>array(
                        'style'=>'height:20px;',
                        'class'=>'span10',
                        'prepend'=>'<i class="icon-calendar">>/i>',    
                        ),
                        ));
         echo"</div>";
         ?>
        </div></div>
        
        <div class='control-group'>
        <?php echo $form->labelEx($model,'data_fim',array('class'=>'control-label')); ?>   
        <div class='controls'>   
         <?php 
         
         echo"<div class='input-prepend'><span class='add-on'><i class='icon-calendar'></i></span>";
         $this->widget('zii.widgets.jui.CJuiDatePicker', array(
                        'model'=>$model,
                        'attribute'=>'data_fim',
                        'value'=>$model->data_fim, 
                        'options'=>array(
                        'dateFormat' => 'yy-mm-dd',
                        'altFormat' => 'yy-mm-dd', // show to user format    
                        'showAnim'=>'fold',
                        ),
                        'htmlOptions'=>array(
                        'style'=>'height:20px;',
                        'class'=>'span10',
                        'prepend'=>'<i class="icon-calendar">>/i>',    
                        ),
                        ));
         echo"</div>";
         ?>
        </div></div>

	<?php
        echo"<div class='control-group'>";
        echo $form->labelEx($model,'imagem',array('class'=>'control-label'));
        echo"<div class='controls'>";
        echo CHtml::activeFileField($model, 'imagem');
        echo"</div></div>";
        
        ?>
        <?php
            if(!$model->isNewRecord)
            {
            echo '<div id="data2">';    
            $this->renderPartial('_imagemContent', array('model'=>$model));
            echo '</div>';
            }
        ?>

<div class="form-actions">
	<?php $this->widget('bootstrap.widgets.TbButton', array(
			'buttonType'=>'submit',
			'type'=>'primary',
			'label'=>$model->isNewRecord ? 'Adicionar' : 'Guardar',
		)); ?>
</div>

<?php $this->endWidget(); ?>

        

dev/protected/views/evento/_imagemContent.php
<?php 
       
if($model->imagem!="")
{

echo"<div class='control-group'>";
    echo"<div class='controls'>";
    echo'<ul class="thumbnails">';
    echo'<li class="span2">
    <div class="thumbnail">
      <img src="'.Yii::app()->request->baseUrl.'/uploads/'.$model->imagem.'" alt="">';
    echo '<div style="text-align:left;margin-top:5px;text-align:center;">'.CHtml::ajaxLink ('<button class="btn btn-mini btn-danger" type="button">Remover imagem</button>',CController::createUrl('evento/UpdateAjax',array('id'=>$model->id)),array('update' => '#data2'));

   echo'</div>
  </li>';
    echo'</ul>';
echo"</div></div>";    
    
   

}
?>

dev/protected/views/evento/_old_news.php
<?php
$titulo="titulo_".Yii::app()->language;
$criteria = new CDbCriteria(array('order'=>'data DESC'));
$news = Noticia::model()->findAllByAttributes(array(),$criteria);
if(sizeof($news)>3)
{
    echo'<aside class="col-sm-3 sidebar">
                        <h3 class="article-title" >'.Content::model()->getContentReturn('noticias-antigas',Yii::app()->language).'</h3>
                        <span class="line" >
                            <span class="sub-line" ></span>
                        </span>';
    echo'<ul class="custom-icon-list categories" >';
    $conta=0;
    foreach ($news as $n)
    {
        $conta++;
        if($conta>3){
        echo'<li><i class="entypo-cd" ></i>';
        echo CHtml::link($n->$titulo,array('view','id'=>$n->id));
        echo'</li>';
        }
    }
    echo'</ul></aside>';
}
?>

dev/protected/views/evento/_search.php
<?php $form=$this->beginWidget('bootstrap.widgets.TbActiveForm',array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

		<?php echo $form->textFieldRow($model,'id',array('class'=>'span5')); ?>

		<?php echo $form->textFieldRow($model,'titulo_pt',array('class'=>'span5','maxlength'=>100)); ?>

		<?php echo $form->textFieldRow($model,'titulo_en',array('class'=>'span5','maxlength'=>100)); ?>

		<?php echo $form->textFieldRow($model,'titulo_fr',array('class'=>'span5','maxlength'=>100)); ?>

		<?php echo $form->textFieldRow($model,'titulo_es',array('class'=>'span5','maxlength'=>100)); ?>

		<?php echo $form->textAreaRow($model,'conteudo_pt',array('rows'=>6, 'cols'=>50, 'class'=>'span8')); ?>

		<?php echo $form->textAreaRow($model,'conteudo_en',array('rows'=>6, 'cols'=>50, 'class'=>'span8')); ?>

		<?php echo $form->textAreaRow($model,'conteudo_fr',array('rows'=>6, 'cols'=>50, 'class'=>'span8')); ?>

		<?php echo $form->textAreaRow($model,'conteudo_es',array('rows'=>6, 'cols'=>50, 'class'=>'span8')); ?>

		<?php echo $form->textFieldRow($model,'data',array('class'=>'span5')); ?>

		<?php echo $form->textFieldRow($model,'imagem',array('class'=>'span5','maxlength'=>45)); ?>

	<div class="form-actions">
		<?php $this->widget('bootstrap.widgets.TbButton', array(
			'buttonType' => 'submit',
			'type'=>'primary',
			'label'=>'Search',
		)); ?>
	</div>

<?php $this->endWidget(); ?>

dev/protected/views/evento/_view.php
<?php
$conteudo="conteudo_".Yii::app()->language;
$titulo="titulo_".Yii::app()->language;
?>
<article class="post">
    <img src="uploads/<?php echo $data->imagem; ?>" alt="//" />
    <header>
        <h3><?php echo CHtml::encode($data->$titulo); ?></h3>
    </header>
    
    <p><?php
    $string = strip_tags($data->$conteudo);

    if (strlen($string) > 300) {
        $stringCut = substr($string, 0, 300);

    $string = substr($stringCut, 0, strrpos($stringCut, ' ')).'...'; 
}
    
    echo $string;
    ?></p>
    <?php echo CHtml::link(Content::model()->getContentReturn('ler-mais',Yii::app()->language).' <i class="entypo-right-open" ></i>',array('view','id'=>$data->id),array('class'=>'readmore')); ?>
    <footer>
        <span><i class="entypo-calendar" ></i><?php echo CHtml::encode($data->data); ?> </span>
    </footer>
</article>

dev/protected/views/evento/admin.php
<div class="row-fluid">
    <div class="span12">

<?php
    $this->beginWidget('bootstrap.widgets.TbBox', array(
    'title' => 'Eventos',
    'headerIcon' => 'icon-globe',
    'headerButtons' => array(
   
    array(
    'class' => 'bootstrap.widgets.TbButtonGroup',
    'buttons'=>array(
    array('label'=>'Adicionar', 'url'=>Yii::app()->baseUrl.'/evento/create'),
    ),
    ),
    )));

$this->pageTitle=Yii::app()->name.' - '."Eventos";

?>

<?php $this->widget('bootstrap.widgets.TbGridView',array(
'id'=>'noticia-grid',
'dataProvider'=>$model->search(),
'filter'=>$model,
'columns'=>array(
                'titulo_pt',
		'data',
                'data_fim',
		/*'titulo_en',
		'titulo_fr',
		'titulo_es',
		'conteudo_pt',
		
		'conteudo_en',
		'conteudo_fr',
		'conteudo_es',
		'data',
		'imagem',
		*/
                array(
			'class'=>'bootstrap.widgets.TbButtonColumn',
			'template'=>'{update} {delete}',
			'buttons'=>array(
                                       
                                        'update' => array
                                        (
                                            //'url'=>'Yii::app()->getController()->createUrl("/itemPortfolio/update",array("id"=>$data->id))',

                                        ),
                                        'delete' => array
                                        (
                                            //'url'=>'Yii::app()->getController()->createUrl("/itemPortfolio/delete",array("id"=>$data->id))',

                                        ),
					),
		),    
),
));
$this->endWidget();
?>

        
</div>
</div>

dev/protected/views/evento/create.php
<div class="row-fluid">
    <div class="span12">

<?php
    $this->beginWidget('bootstrap.widgets.TbBox', array(
    'title' => 'Adicionar Evento',
    'headerIcon' => 'icon-globe',
    'headerButtons' => array(
   
    array(
    'class' => 'bootstrap.widgets.TbButtonGroup',
    'buttons'=>array(
    array('label'=>'Gerir Eventos', 'url'=>Yii::app()->baseUrl.'/evento/admin'),
    ),
    ),
    )));

$this->pageTitle=Yii::app()->name.' - '."Adicionar Evento";

?>

<?php echo $this->renderPartial('_form', array('model'=>$model));

$this->endWidget();
?>


</div>
</div>

dev/protected/views/evento/index.php
<?php
$this->pageTitle=Yii::app()->name . ' - '.mb_strtoupper(Content::model()->getContentReturn('eventos',Yii::app()->language),"UTF-8");
$titulo="titulo_".Yii::app()->language;
$conteudo="conteudo_".Yii::app()->language;
?>
<div class="container-fluid fundo hidden-xs">
    <div class="container sombra">
        <?php
        $menu=Menu::model()->findByAttributes(array("link"=>"evento"));
        echo'<img src="'.Yii::app()->baseUrl.'/uploads/'.$menu->imagem.'" width="100%">';
        ?>
        
    </div>
</div>
<div class="container branco">
    <div class="texto">
                
            <?php
            $model=$dataProvider->getData();
            
            foreach($model as $m)
            {
                if($m->link!=null)
                    $link=$m->link;
                else
                    $link="#";
                echo'<div class="row">
                    <div class="col-md-offset-2 col-md-5">
                        <h5><a href="'.$link.'" target="_blank"><i class="fa fa-calendar"></i>&nbsp;'.mb_strtoupper($m->$titulo,"UTF-8").' '.$m->data.' a '.$m->data_fim.'</a></h5>
                        '.$m->$conteudo.'
                    </div>
                    <div class="col-md-3">
                        <img src="'.Yii::app()->baseUrl.'/uploads/'.$m->imagem.'" style="max-width: 400px;">
                    </div>
                </div>
                <br>
                <br>';
            }
            ?>
            
               
            </div>
        </div>
    </div>
</div>

<br>
<br>

dev/protected/views/evento/update.php
<div class="row-fluid">
    <div class="span12">

<?php
    $this->beginWidget('bootstrap.widgets.TbBox', array(
    'title' => 'Editar Evento '.$model->titulo_pt,
    'headerIcon' => 'icon-globe',
    'headerButtons' => array(
   
    array(
    'class' => 'bootstrap.widgets.TbButtonGroup',
    'buttons'=>array(
    array('label'=>'Gerir Eventos', 'url'=>Yii::app()->baseUrl.'/evento/admin'),
    ),
    ),
    )));

$this->pageTitle=Yii::app()->name.' - '."Editar Evento ".$model->titulo_pt;

?>

<?php echo $this->renderPartial('_form', array('model'=>$model));

$this->endWidget();
?>


</div>
</div>

dev/protected/views/evento/view.php
<?php
$conteudo="conteudo_".Yii::app()->language;
$titulo="titulo_".Yii::app()->language;
$this->pageTitle=Yii::app()->name . ' - '.$model->$titulo;
?>
<!-- begin Content -->
    <section id="single-news" >
        <!-- begin Sub Header -->
        <div class="sub-header" >
            <div class="container">
                <div class="row" >
                    <ul class="sub-header-container" >
                        <li>
                            <h3 class="title"><?php echo $model->$titulo; ?></h3>
                        </li>
                        <li>
                            <ul class="custom-breadcrumb" >
                                <li><h6><a href="index.php">Home</a></h6></li>
                                <li><i class="separator entypo-play" ></i></li>
                                <li><h6><?php echo CHtml::link(Content::model()->getContentReturn('evento',Yii::app()->language),array('index')); ?></h6></li>
                                <li><i class="separator entypo-play" ></i></li>
                                <li><h6><?php echo $model->$titulo; ?></h6></li>
                            </ul>                    
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <!-- begin Sub Header -->


        <!-- begin New -->
        <article class="article-container">
            <div class="container" >
                <div class="row" >
                    <div class="col-md-9">
                        <h2 class="article-title" ><?php echo $model->$titulo; ?></h2>
                        <span class="line" >
                            <span class="sub-line" ></span>
                        </span>

                        <!-- begin Post -->
                        <section class="row">
                            <article class="post">
                                <img src="uploads/<?php echo $model->imagem; ?>" alt="//" />
                                <p></p>
                                <?php /* ?><p><label class="cap" ><?php echo substr($model->$conteudo, 0, 1); ?></label><?php echo substr($model->$conteudo, 1, strlen($model->$conteudo)); ?></p><?php */ ?>
                                <p><?php echo $model->$conteudo; ?></p>
                                <?php echo CHtml::link('<i class="entypo-left-open" ></i> '.Content::model()->getContentReturn('voltar',Yii::app()->language),array('index'),array('class'=>'readmore')); ?>  
                            </article>
                        </section>
                        <!-- end Post -->

                    </div>

                    <!-- begin Sidebar -->
                    <?php
                    $this->renderPartial('_all_news');
                    ?>
                    <!-- end Sidebar -->
                </div>
            </div>
        </article>
        <!-- end New -->
        
    </section>
    <!-- end Content -->