protected/models/Categoria.php
<?php

/**
 * This is the model class for table "categoria".
 *
 * The followings are the available columns in table 'categoria':
 * @property integer $id
 * @property string $nome_pt
 * @property string $nome_en
 * @property integer $ordem
 */
class Categoria extends CActiveRecord
{
	/**
	 * Returns the static model of the specified AR class.
	 * @param string $className active record class name.
	 * @return Categoria the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'categoria';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('nome_pt, area_atividade_id', 'required'),
                        array('slug_pt, slug_en, slug_es', 'safe'),
			array('ordem, categoria_main', 'numerical', 'integerOnly'=>true),
			array('nome_pt, nome_en, nome_fr, nome_es', 'length', 'max'=>100),
			// The following rule is used by search().
			// Please remove those attributes that should not be searched.
			array('id, nome_pt, nome_en, nome_fr, nome_es, ordem, categoria_main', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
                    'Categoria2' => array(self::BELONGS_TO, 'Categoria', 'categoria_main'),
                    'Area' => array(self::BELONGS_TO, 'AreaAtividade', 'area_atividade_id'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'nome_pt' => 'Nome PT',
			'nome_en' => 'Nome EN',
                        'nome_fr' => 'Nome FR',
                        'nome_es' => 'Nome ES',
                        'categoria_main'=>'Categoria Principal',
			'ordem' => 'Ordem',
                        'area_atividade_id'=>'Área de Atividade',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
	 */
	public function search()
	{
		// Warning: Please modify the following code to remove attributes that
		// should not be searched.

		$criteria=new CDbCriteria;
                
                $criteria->with = array('Categoria2','Area');
                
                
		$criteria->compare('id',$this->id);
                $criteria->compare('t.nome_pt',$this->categoria_main,true);
                $criteria->compare('t.nome_pt',$this->nome_pt,true);
		//$criteria->compare('t.nome_en',$this->nome_en,true);
                //$criteria->compare('t.nome_fr',$this->nome_fr,true);
                //$criteria->compare('t.nome_es',$this->nome_es,true);
		//$criteria->compare('t.ordem',$this->ordem);
                $criteria->compare('Area.nome_pt',$this->area_atividade_id,true);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
                        'sort'=>array(
                            'defaultOrder'=>'Area.nome_pt ASC, Categoria2.nome_pt ASC, t.nome_pt ASC',
                          )
		));
	}
        
        
        public function getAllName()
        {
            $todos=$this->findAll(array('order'=>nome_pt));
            $arr = array();
            foreach($todos as $t)
            {
                if($t->categoria_main==null)
                    $arr[$t->id] = $t->nome_pt;
                else
                {
                    $categoria_main=$this->findByPk($t->categoria_main);
                    $arr[$t->id] = $categoria_main->nome_pt." > ".$t->nome_pt;
                }
            }
            return $arr;
        }
        
        public function getAllNameMain()
        {
            $criteria = new CDbCriteria();
            $criteria->condition = 'categoria_main IS NULL';
            $criteria->order='nome_pt';
            $todos = $this->findAll($criteria);
            $arr = array();
            foreach($todos as $t)
            {
                if($t->categoria_main==null)
                    $arr[$t->id] = $t->nome_pt;
                else
                {
                    $categoria_main=$this->findByPk($t->categoria_main);
                    $arr[$t->id] = $categoria_main->nome_pt." > ".$t->nome_pt;
                }
            }
            return $arr;
        }
        
        public function getAllNameNotMain()
        {
            $criteria = new CDbCriteria();
            //$criteria->condition = 'categoria_main IS NOT NULL';
            $criteria->order='nome_pt';
            $todos = $this->findAll($criteria);
            $arr = array();
            foreach($todos as $t)
            {
                if($t->categoria_main==null)
                    $arr[$t->id] = $t->nome_pt;
                else
                {
                    $categoria_main=$this->findByPk($t->categoria_main);
                    $arr[$t->id] = $categoria_main->nome_pt." > ".$t->nome_pt;
                }
            }
            //var_dump($arr);
            asort($arr,2);
            //echo "<br>";
            //var_dump($arr);
            
            //die;
            return $arr;
        }
        
        public function getById($id)
        {
            $model=$this->findByPk($id);   
            if($model!=null)
                return $model->nome_pt;
            else
                return "N/A";
        }
        
        public function getAllNameExclude($categoria_id)
        {
            $criteria = new CDbCriteria();
            $criteria->condition = 'id!=:id AND categoria_main IS NULL';
            $criteria->params = array(':id'=>$categoria_id);
            $todos = $this->findAll($criteria);

            $arr = array();
            foreach($todos as $t)
            {
                $arr[$t->id] = $t->nome_pt;
            }
            return $arr;
        }
}

protected/controllers/CategoriaController.php
<?php

class CategoriaController extends Controller
{
/**
* @var string the default layout for the views. Defaults to '//layouts/column2', meaning
* using two-column layout. See 'protected/views/layouts/column2.php'.
*/
public $layout='//layouts/column2';

/**
* @return array action filters
*/
public function filters()
{
return array(
'accessControl', // perform access control for CRUD operations
);
}

/**
* Specifies the access control rules.
* This method is used by the 'accessControl' filter.
* @return array access control rules
*/
public function accessRules()
{
return array(
array('allow',  // allow all users to perform 'index' and 'view' actions
'actions'=>array('view'),
'users'=>array('*'),
),
    
array('allow', // allow admin user to perform 'admin' and 'delete' actions
'actions'=>array('admin','delete','create','update'),
'roles'=>array('admin'),
),
array('deny',  // deny all users
'users'=>array('*'),
),
);
}

/**
* Displays a particular model.
* @param integer $id the ID of the model to be displayed
*/
public function actionView($id)
{
    
$this->layout="//layouts/column1";
$model=Categoria::model()->findByPk($id);

$model2=new ContactForm;
if(isset($_POST['ContactForm']))
{

        $model2->attributes=$_POST['ContactForm'];
        if($model2->validate())
        {
                $pedido=new Pedido;
                $pedido->attributes=$model2->attributes;
                $pedido->data=date("Y-m-d H:i:s");
                $pedido->nome=$model2->name;
                $pedido->cod_postal=$model2->codpostal;
                $pedido->mensagem=$model2->body;
                $pedido->save(false);
            
                $assunto=$model2['assunto'];
                $subject='Máq. Equip. '.$assunto;
                $mail = new YiiMailer();
                $mail->setFrom($model2->email, $model2->name);
                $mail->setTo(Yii::app()->params['adminEmail']);
                //$mail->setTo("mail@norberto.eu");
                $mail->setSubject($subject);
                
                $mensagem="Nome: ".$model2->name."<br>";
                $mensagem.="Empresa: ".$model2->empresa."<br>";
                $mensagem.="Telemóvel: ".$model2->telemovel."<br>";
                $mensagem.="E-mail: ".$model2->email."<br>";
                $mensagem.="Código Postal: ".$model2->codpostal."<br>";
                $mensagem.="Mensagem: ".$model2->body."<br>";
                $mail->setBody($mensagem);
                $mail->send();
                Yii::app()->user->setFlash('contact','Obrigado por nos contactar. Entraremos em contacto consigo o mais breve possível.');
                $this->refresh();
        }
}

if($model===null){    
    $model=Categoria::model()->findByAttributes(array('slug_pt'=>$id));    
}

if($model===null)
    throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');  

$area_escolhida=AreaAtividade::model()->findByPk($model->area_atividade_id);

    
$areas_atividade=AreaAtividade::model()->findAll(array('order'=>'ordem ASC'));

$Criteria = new CDbCriteria();
$Criteria->condition = "area_atividade_id = ".$area_escolhida->id." AND categoria_main IS NULL";
$Criteria->order="ordem ASC";
$categorias = Categoria::model()->findAll($Criteria);

$Criteria = new CDbCriteria();
$Criteria->condition = "categoria_id = ".$model->id;
$Criteria->order="ordem ASC";
$maquinas = Maquina::model()->findAll($Criteria);

$this->render('view',array(
'model'=>$model,'areas_atividade'=>$areas_atividade,'categorias'=>$categorias,'area_escolhida'=>$area_escolhida,'maquinas'=>$maquinas,'model2'=>$model2
));
}

/**
* Creates a new model.
* If creation is successful, the browser will be redirected to the 'view' page.
*/
public function actionCreate()
{
$model=new Categoria;

// Uncomment the following line if AJAX validation is needed
// $this->performAjaxValidation($model);

if(isset($_POST['Categoria']))
{
$model->attributes=$_POST['Categoria'];
$model->slug_pt=Pagina::model()->toAscii($model->nome_pt);
$model->slug_es=Pagina::model()->toAscii($model->nome_es);
$model->slug_en=Pagina::model()->toAscii($model->nome_en);

if($model->save())
$this->redirect(array('admin'));
}

$this->render('create',array(
'model'=>$model,
));
}

/**
* Updates a particular model.
* If update is successful, the browser will be redirected to the 'view' page.
* @param integer $id the ID of the model to be updated
*/
public function actionUpdate($id)
{
$model=$this->loadModel($id);

// Uncomment the following line if AJAX validation is needed
// $this->performAjaxValidation($model);

if(isset($_POST['Categoria']))
{
$model->attributes=$_POST['Categoria'];
$model->slug_pt=Pagina::model()->toAscii($model->nome_pt);
$model->slug_es=Pagina::model()->toAscii($model->nome_es);
$model->slug_en=Pagina::model()->toAscii($model->nome_en);

if($model->save())
$this->redirect(array('admin'));
}

$this->render('update',array(
'model'=>$model,
));
}

/**
* Deletes a particular model.
* If deletion is successful, the browser will be redirected to the 'admin' page.
* @param integer $id the ID of the model to be deleted
*/
public function actionDelete($id)
{
if(Yii::app()->request->isPostRequest)
{
// we only allow deletion via POST request
$this->loadModel($id)->delete();

// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
if(!isset($_GET['ajax']))
$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
}
else
throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
}

/**
* Lists all models.
*/
public function actionIndex()
{
$dataProvider=new CActiveDataProvider('Categoria');
$this->render('index',array(
'dataProvider'=>$dataProvider,
));
}

/**
* Manages all models.
*/
public function actionAdmin()
{
$model=new Categoria('search');
$model->unsetAttributes();  // clear any default values
if(isset($_GET['Categoria']))
$model->attributes=$_GET['Categoria'];

$this->render('admin',array(
'model'=>$model,
));
}

/**
* Returns the data model based on the primary key given in the GET variable.
* If the data model is not found, an HTTP exception will be raised.
* @param integer the ID of the model to be loaded
*/
public function loadModel($id)
{
$model=Categoria::model()->findByPk($id);
if($model===null)
throw new CHttpException(404,'The requested page does not exist.');
return $model;
}

/**
* Performs the AJAX validation.
* @param CModel the model to be validated
*/
protected function performAjaxValidation($model)
{
if(isset($_POST['ajax']) && $_POST['ajax']==='categoria-form')
{
echo CActiveForm::validate($model);
Yii::app()->end();
}
}
}

protected/views/categoria/_form.php
<?php $form=$this->beginWidget('bootstrap.widgets.TbActiveForm',array(
	'id'=>'categoria-form',
	'enableAjaxValidation'=>false,
)); ?>

<p class="help-block">Os campos com <span class="required">*</span> são obrigatórios.</p>

<?php echo $form->errorSummary($model); ?>
        
        <div class='control-group'>
        <?php echo $form->labelEx($model,'area_atividade_id',array('class'=>'control-label')); ?>   
        <div class='controls'>
        <?php
            echo $form->dropDownList($model,'area_atividade_id',AreaAtividade::model()->getAllName(),array('class'=>'span4','prompt'=>'Escolha a área de atividade'));
        ?>
        </div></div>

        <div class='control-group'>
        <?php echo $form->labelEx($model,'categoria_main',array('class'=>'control-label')); ?>   
        <div class='controls'>
        <?php
        if($model->isNewRecord)
            echo $form->dropDownList($model,'categoria_main',Categoria::model()->getAllNameMain(),array('class'=>'span4','prompt'=>'Escolha a categoria'));
        else
            echo $form->dropDownList($model,'categoria_main',Categoria::model()->getAllNameExclude($model->id),array('class'=>'span4','prompt'=>'Escolha a categoria'));
        
        ?>
        </div></div>
        
	<?php echo $form->textFieldRow($model,'nome_pt',array('class'=>'span6','maxlength'=>100)); ?>

	<?php //echo $form->textFieldRow($model,'nome_en',array('class'=>'span6','maxlength'=>100)); ?>

        <?php //echo $form->textFieldRow($model,'nome_fr',array('class'=>'span6','maxlength'=>100)); ?>

        <?php echo $form->textFieldRow($model,'nome_es',array('class'=>'span6','maxlength'=>100)); ?>

	<?php echo $form->textFieldRow($model,'ordem',array('class'=>'span1')); ?>

<div class="form-actions">
	<?php $this->widget('bootstrap.widgets.TbButton', array(
			'buttonType'=>'submit',
			'type'=>'primary',
			'label'=>$model->isNewRecord ? 'Adicionar' : 'Guardar',
		)); ?>
</div>

<?php $this->endWidget(); ?>

protected/views/categoria/_search.php
<?php $form=$this->beginWidget('bootstrap.widgets.TbActiveForm',array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

		<?php echo $form->textFieldRow($model,'id',array('class'=>'span5')); ?>

		<?php echo $form->textFieldRow($model,'nome_pt',array('class'=>'span5','maxlength'=>50)); ?>

		<?php echo $form->textFieldRow($model,'nome_en',array('class'=>'span5','maxlength'=>50)); ?>

		<?php echo $form->textFieldRow($model,'ordem',array('class'=>'span5')); ?>

	<div class="form-actions">
		<?php $this->widget('bootstrap.widgets.TbButton', array(
			'buttonType' => 'submit',
			'type'=>'primary',
			'label'=>'Search',
		)); ?>
	</div>

<?php $this->endWidget(); ?>

protected/views/categoria/_view.php
<div class="view">

		<b><?php echo CHtml::encode($data->getAttributeLabel('id')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->id),array('view','id'=>$data->id)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('nome_pt')); ?>:</b>
	<?php echo CHtml::encode($data->nome_pt); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('nome_en')); ?>:</b>
	<?php echo CHtml::encode($data->nome_en); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('ordem')); ?>:</b>
	<?php echo CHtml::encode($data->ordem); ?>
	<br />


</div>

protected/views/categoria/admin.php
<div class="row-fluid">
    <div class="span12">

<?php
    $this->beginWidget('bootstrap.widgets.TbBox', array(
    'title' => 'Categorias',
    'headerIcon' => 'icon-folder-open',
    'headerButtons' => array(
   
    array(
    'class' => 'bootstrap.widgets.TbButtonGroup',
    'buttons'=>array(
    array('label'=>'Adicionar', 'url'=>Yii::app()->baseUrl.'/categoria/create'),
    ),
    ),
    )));

$this->pageTitle=Yii::app()->name.' - '."Categorias";
$this->breadcrumbs=array(
	'Categorias'=>array('index'),
	'Manage',
);


?>



<?php $this->widget('bootstrap.widgets.TbGridView',array(
'id'=>'categoria-grid',
'dataProvider'=>$model->search(),
'filter'=>$model,
'columns'=>array(
                array(
                    'name'=>'area_atividade_id',
                    'type'=>'raw',
                    'value'=>'AreaAtividade::model()->getById($data->area_atividade_id)',
                ),
                array(
                    'name'=>'categoria_main',
                    'type'=>'raw',
                    'value'=>'Categoria::model()->getById($data->categoria_main)',
                ),
                //'id',
		'nome_pt',
		//'nome_en',
                array(
                    'name'=>'ordem',
                    'value'=>'$data->ordem',
                    'filter'=>false,
                    ),
array(
			'class'=>'bootstrap.widgets.TbButtonColumn',
			'template'=>'{update} {delete}',
			'buttons'=>array(
                                        'update' => array
                                        (
                                            'url'=>'Yii::app()->getController()->createUrl("/categoria/update",array("id"=>$data->id))',

                                        ),
                                        'delete' => array
                                        (
                                            'url'=>'Yii::app()->getController()->createUrl("/categoria/delete",array("id"=>$data->id))',

                                        ),
					),
		),
),
)); 


$this->endWidget();
?>


</div>
</div>

protected/views/categoria/create.php
<div class="row-fluid">
    <div class="span12">

<?php
    $this->beginWidget('bootstrap.widgets.TbBox', array(
    'title' => 'Adicionar categoria',
    'headerIcon' => 'icon-folder-open',
    'headerButtons' => array(
   
    array(
    'class' => 'bootstrap.widgets.TbButtonGroup',
    'buttons'=>array(
    array('label'=>'Gerir categorias', 'url'=>Yii::app()->baseUrl.'/categoria/admin'),
    ),
    ),
    )));

$this->pageTitle=Yii::app()->name.' - '."Adicionar categoria";
$this->breadcrumbs=array(
	'Categorias'=>array('index'),
	'Manage',
);


?>

<?php echo $this->renderPartial('_form', array('model'=>$model));

$this->endWidget();
?>


</div>
</div>

protected/views/categoria/index.php
<?php
$this->breadcrumbs=array(
	'Categorias',
);

$this->menu=array(
array('label'=>'Create Categoria','url'=>array('create')),
array('label'=>'Manage Categoria','url'=>array('admin')),
);
?>

<h1>Categorias</h1>

<?php $this->widget('bootstrap.widgets.TbListView',array(
'dataProvider'=>$dataProvider,
'itemView'=>'_view',
)); ?>

protected/views/categoria/update.php
<div class="row-fluid">
    <div class="span12">

<?php
    $this->beginWidget('bootstrap.widgets.TbBox', array(
    'title' => 'Editar categoria '.$model->nome_pt,
    'headerIcon' => 'icon-folder-open',
    'headerButtons' => array(
   
    array(
    'class' => 'bootstrap.widgets.TbButtonGroup',
    'buttons'=>array(
    array('label'=>'Gerir categorias', 'url'=>Yii::app()->baseUrl.'/categoria/admin'),
    ),
    ),
    )));

$this->pageTitle=Yii::app()->name.' - '."Editar categoria ".$model->nome_pt;
$this->breadcrumbs=array(
	'Categorias'=>array('index'),
	'Manage',
);


?>

<?php echo $this->renderPartial('_form', array('model'=>$model));

$this->endWidget();
?>


</div>
</div>