protected/models/Ficheiro.php
<?php

/**
 * This is the model class for table "ficheiro".
 *
 * The followings are the available columns in table 'ficheiro':
 * @property integer $id
 * @property string $src
 */
class Ficheiro extends CActiveRecord
{
	/**
	 * Returns the static model of the specified AR class.
	 * @param string $className active record class name.
	 * @return Ficheiro the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'ficheiro';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('src', 'required'),
			array('src, titulo_pt, titulo_en, titulo_fr, titulo_es', 'length', 'max'=>200),
			// The following rule is used by search().
			// Please remove those attributes that should not be searched.
			array('id, src, titulo_pt, titulo_en, titulo_fr, titulo_es', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'src' => 'Ficheiro',
                        'titulo_pt'=>'Título PT',
                        'titulo_en'=>'Título EN',
                        'titulo_fr'=>'Título FR',
                        'titulo_es'=>'Título ES',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
	 */
	public function search()
	{
		// Warning: Please modify the following code to remove attributes that
		// should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id);
		$criteria->compare('src',$this->src,true);
                $criteria->compare('titulo_pt',$this->titulo_pt,true);
                $criteria->compare('titulo_en',$this->titulo_en,true);
                $criteria->compare('titulo_fr',$this->titulo_fr,true);
                $criteria->compare('titulo_es',$this->titulo_es,true);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}
        
        public function fileType($id)
        {
            $model=$this->findByPk($id);  
            $type=explode(".",$model->src);
            if($type[1]==="pdf")
                return true;
            else
                return false;
        }
        
        public function lerFicheiros(){
            $url=Website::model()->findByPk(1);
                if($url!=null)
                    $url = $url->url;
                else
                    $url="";
            if ($handle = opendir(Yii::getPathOfAlias('webroot').'/uploads/gestor/')) {
                $file = fopen(Yii::getPathOfAlias('webroot').'/uploads/image_list_agricortes.js',"w+");
                $conteudo="[";
                while (false !== ($entry = readdir($handle))) {
                    if($entry!="." && $entry!=".."){
                        $conteudo.="{\"image\": \"".$url."/uploads/gestor/".$entry."\"},";
                    }
            }
            $conteudo=substr_replace($conteudo ,"",-1);
            $conteudo.="]";
            fwrite($file,$conteudo);
            fclose($file);
            closedir($handle);
            }
        }
}

protected/controllers/FicheiroController.php
<?php

class FicheiroController extends Controller
{
/**
* @var string the default layout for the views. Defaults to '//layouts/column2', meaning
* using two-column layout. See 'protected/views/layouts/column2.php'.
*/
public $layout='//layouts/column2';

/**
* @return array action filters
*/
public function filters()
{
return array(
'accessControl', // perform access control for CRUD operations
);
}

/**
* Specifies the access control rules.
* This method is used by the 'accessControl' filter.
* @return array access control rules
*/
public function accessRules()
{
return array(

array('allow', // allow admin user to perform 'admin' and 'delete' actions
'actions'=>array('admin','delete','create','update','view','updateajax','download'),
'roles'=>array('admin'),
),
array('deny',  // deny all users
'users'=>array('*'),
),
);
}

/**
* Displays a particular model.
* @param integer $id the ID of the model to be displayed
*/
public function actionView($id)
{
$this->render('view',array(
'model'=>$this->loadModel($id),
));
}

/**
* Creates a new model.
* If creation is successful, the browser will be redirected to the 'view' page.
*/
public function actionCreate()
{
$model=new Ficheiro;

// Uncomment the following line if AJAX validation is needed
// $this->performAjaxValidation($model);

if(isset($_POST['Ficheiro']))
{
$model->attributes=$_POST['Ficheiro'];

$rnd = md5(time());

$uploadedFile=CUploadedFile::getInstance($model,'src');

if(!empty($uploadedFile))
{
    $fileName = "{$rnd}.{$uploadedFile->extensionName}";
    $fileBaseName = basename($uploadedFile,'.'.$uploadedFile->extensionName);
    $model->src = $fileName;
    $model->titulo_pt=$fileBaseName;
}

if($model->save())
{
    if(!empty($uploadedFile)){   
        $uploadedFile->saveAs(Yii::getPathOfAlias('webroot').'/uploads/gestor/'.$fileName);
    }
    
    Ficheiro::model()->lerFicheiros();
    
    $this->redirect(array('admin'));
}
}

$this->render('create',array(
'model'=>$model,
));
}


/**
* Updates a particular model.
* If update is successful, the browser will be redirected to the 'view' page.
* @param integer $id the ID of the model to be updated
*/
public function actionUpdate($id)
{
$model=$this->loadModel($id);

// Uncomment the following line if AJAX validation is needed
// $this->performAjaxValidation($model);
$imagem_antiga=$model->src;

if(isset($_POST['Ficheiro']))
{
    $rnd = md5(time());
    $model->attributes=$_POST['Ficheiro'];
    $uploadedFile=CUploadedFile::getInstance($model,'src');
    if(!empty($uploadedFile))
        {
            $fileName = "{$rnd}.{$uploadedFile->extensionName}";
            $fileBaseName = basename($uploadedFile,'.'.$uploadedFile->extensionName);
            $model->src = $fileName;
            $model->titulo_pt=$fileBaseName;
            
            $old_file=Ficheiro::model()->findByPk($id)->src;
            if ($old_file!="" && $old_file!=null && file_exists(Yii::getPathOfAlias('webroot').'/uploads/gestor/'. $old_file))
                unlink(Yii::getPathOfAlias('webroot').'/uploads/gestor/'. $old_file);
        }
        elseif($imagem_antiga!="" && $imagem_antiga!=null)
         $model->src=$imagem_antiga;
    
if($model->save()){
    if(!empty($uploadedFile))  
    {
        $uploadedFile->saveAs(Yii::app()->basePath.'/../uploads/gestor/'.$model->src);
        //Ficheiro::model()->createThumbnails(Yii::getPathOfAlias('webroot').'/uploads/',$fileName);
    }
    
    Ficheiro::model()->lerFicheiros();
    
    $this->redirect(array('admin'));
}
}

$this->render('update',array(
'model'=>$model,
));
}

/**
* Deletes a particular model.
* If deletion is successful, the browser will be redirected to the 'admin' page.
* @param integer $id the ID of the model to be deleted
*/
public function actionDelete($id)
{
if(Yii::app()->request->isPostRequest)
{
$old_file=Ficheiro::model()->findByPk($id)->src;
if ($old_file!="" && $old_file!=null && file_exists(Yii::getPathOfAlias('webroot').'/uploads/gestor/'. $old_file))
    unlink(Yii::getPathOfAlias('webroot').'/uploads/gestor/'. $old_file);     
// we only allow deletion via POST request
$this->loadModel($id)->delete();
Ficheiro::model()->lerFicheiros();
// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
if(!isset($_GET['ajax']))
$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
}
else
throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
}


/**
* Lists all models.
*/
public function actionIndex()
{
$dataProvider=new CActiveDataProvider('Ficheiro');
$this->render('index',array(
'dataProvider'=>$dataProvider,
));
}

/**
* Manages all models.
*/
public function actionAdmin()
{
$model=new Ficheiro('search');
$model->unsetAttributes();  // clear any default values
if(isset($_GET['Ficheiro']))
$model->attributes=$_GET['Ficheiro'];

$this->render('admin',array(
'model'=>$model,
));
}

/**
* Returns the data model based on the primary key given in the GET variable.
* If the data model is not found, an HTTP exception will be raised.
* @param integer the ID of the model to be loaded
*/
public function loadModel($id)
{
$model=Ficheiro::model()->findByPk($id);
if($model===null)
throw new CHttpException(404,'The requested page does not exist.');
return $model;
}

/**
* Performs the AJAX validation.
* @param CModel the model to be validated
*/
protected function performAjaxValidation($model)
{
if(isset($_POST['ajax']) && $_POST['ajax']==='ficheiro-form')
{
echo CActiveForm::validate($model);
Yii::app()->end();
}
}

public function actionUpdateAjax($id)
{
    $model=Ficheiro::model()->findByPk($id);
    $fileName=$model->src;
    $model->src="";
    $model->save(false);
    if (file_exists(Yii::getPathOfAlias('webroot').'/uploads/gestor/'. $fileName))
        unlink(Yii::getPathOfAlias('webroot').'/uploads/gestor/'. $fileName);

    $this->renderPartial('_imagemContent', array('model'=>$model));
}

/*public function actionDownload($id)
        {
        $model=Ficheiro::model()->findByPk($id);
        $path = Yii::app()->request->hostInfo . Yii::app()->request->baseURL . '/uploads/' . $model->src;  
        $extension=explode(".",$model->src);
        return Yii::app()->getRequest()->sendFile($model->titulo_pt. $extension[1], @file_get_contents($path));  
        }*/
        public function actionDownload($id)
        {

            $model=Ficheiro::model()->findByPk($id);
            $path = Yii::app()->request->hostInfo . Yii::app()->request->baseURL . '/uploads/gestor/' . $model->src;
            $extension=explode(".",$model->src);
            return Yii::app()->getRequest()->sendFile($model->titulo_pt .".". $extension[1] , Yii::app()->curl->get($path));
        }

}

protected/views/ficheiro/_form.php
<?php $form=$this->beginWidget('bootstrap.widgets.TbActiveForm',array(
	'id'=>'slider-form',
	'enableAjaxValidation'=>false,
        'htmlOptions' => array(
            'enctype' => 'multipart/form-data',
        ),
)); ?>

<p class="help-block">Os campos com <span class="required">*</span> são obrigatórios.</p>

<?php echo $form->errorSummary($model); ?>

        <?php echo $form->textFieldRow($model,'titulo_pt',array('class'=>'span8','maxlength'=>100)); ?>

	<?php echo $form->textFieldRow($model,'titulo_es',array('class'=>'span8','maxlength'=>100)); ?>

	<?php
        echo"<div class='control-group'>";
        echo $form->labelEx($model,'src',array('class'=>'control-label'));
        echo"<div class='controls'>";
        echo CHtml::activeFileField($model, 'src');
        echo"</div></div>";
        ?>
        
        <?php
            if(!$model->isNewRecord)
            {
            echo '<div id="data2">';    
            $this->renderPartial('_imagemContent', array('model'=>$model));
            echo '</div>';
            }
        ?>

	

<div class="form-actions">
	<?php $this->widget('bootstrap.widgets.TbButton', array(
			'buttonType'=>'submit',
			'type'=>'primary',
			'label'=>$model->isNewRecord ? 'Adicionar' : 'Guardar',
		)); ?>
</div>

<?php $this->endWidget(); ?>

protected/views/ficheiro/_imagemContent.php
<?php 
if($model->src!="")
{

$extension=explode(".",$model->src);

if($extension[1]==="pdf"){
    echo"<div class='control-group'>";
    echo"<div class='controls'>";
    echo CHtml::link('<i class="icon-download-alt"> '.$model->titulo_pt.'</i>', array("Ficheiro/download", "id"=>$model->id));
    echo"</div></div>"; 
}
else
{
    
    
echo"<div class='control-group'>";
    echo"<div class='controls'>";
    echo'<ul class="thumbnails">';
    echo'<li class="span2">
    <div class="thumbnail">
      <img src="'.Yii::app()->request->baseUrl.'/uploads/'.$model->src.'" alt="">';
 //echo '<div style="text-align:left;margin-top:5px;text-align:center;">'.CHtml::ajaxLink ('<button class="btn btn-mini btn-danger" type="button">Remover imagem</button>',CController::createUrl('ficheiro/UpdateAjax',array('id'=>$model->id)),array('update' => '#data2'));

   echo'</div>
  </li>';
    echo'</ul>';
echo"</div></div>";    
    
}   

}
?>

protected/views/ficheiro/_search.php
<?php $form=$this->beginWidget('bootstrap.widgets.TbActiveForm',array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

		<?php echo $form->textFieldRow($model,'id',array('class'=>'span5')); ?>

		<?php echo $form->textFieldRow($model,'src',array('class'=>'span5','maxlength'=>200)); ?>

	<div class="form-actions">
		<?php $this->widget('bootstrap.widgets.TbButton', array(
			'buttonType' => 'submit',
			'type'=>'primary',
			'label'=>'Search',
		)); ?>
	</div>

<?php $this->endWidget(); ?>

protected/views/ficheiro/_view.php
<div class="view">

		<b><?php echo CHtml::encode($data->getAttributeLabel('id')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->id),array('view','id'=>$data->id)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('src')); ?>:</b>
	<?php echo CHtml::encode($data->src); ?>
	<br />


</div>

protected/views/ficheiro/admin.php
<div class="row-fluid">
    <div class="span12">

<?php
    $this->beginWidget('bootstrap.widgets.TbBox', array(
    'title' => 'Gestão de Ficheiros',
    'headerIcon' => 'icon-file',
    'headerButtons' => array(
   
    array(
    'class' => 'bootstrap.widgets.TbButtonGroup',
    'buttons'=>array(
    array('label'=>'Adicionar', 'url'=>Yii::app()->baseUrl.'/ficheiro/create'),
    ),
    ),
    )));

$this->pageTitle=Yii::app()->name.' - '."Gestão de Ficheiros";

?>

<?php $this->widget('bootstrap.widgets.TbGridView',array(
'id'=>'publicidade-grid',
'dataProvider'=>$model->search(),
'filter'=>$model,
'columns'=>array(
		'titulo_pt',
		array(
                    'name'=>'src',
                    'type'=>'raw',
                    'filter'=>false,
                    'value'=>'(Ficheiro::model()->fileType($data->id))? "N/A" : CHtml::image(Yii::app()->request->baseUrl."/uploads/gestor/".$data->src,"src",array("width"=>100,"class"=>"img-polaroid"))',
                ),
                
		
        array(
			'class'=>'bootstrap.widgets.TbButtonColumn',
			'template'=>'{download} {update} {delete}',
			'buttons'=>array(
                                        'download' => array
                                        (
                                            'url'=>'Yii::app()->getController()->createUrl("/Ficheiro/download",array("id"=>$data->id))',

                                        ),
                            
                                        'update' => array
                                        (
                                            //'url'=>'Yii::app()->getController()->createUrl("/itemPortfolio/update",array("id"=>$data->id))',

                                        ),
                                        'delete' => array
                                        (
                                            //'url'=>'Yii::app()->getController()->createUrl("/itemPortfolio/delete",array("id"=>$data->id))',

                                        ),
					),
		),    
    
),
));
$this->endWidget();
?>

</div>
</div>

protected/views/ficheiro/create.php
<div class="row-fluid">
    <div class="span12">

<?php
    $this->beginWidget('bootstrap.widgets.TbBox', array(
    'title' => 'Adicionar Ficheiro',
    'headerIcon' => 'icon-file',
    'headerButtons' => array(
   
    array(
    'class' => 'bootstrap.widgets.TbButtonGroup',
    'buttons'=>array(
    array('label'=>'Gerir Ficheiros', 'url'=>Yii::app()->baseUrl.'/ficheiro/admin'),
    ),
    ),
    )));

$this->pageTitle=Yii::app()->name.' - '."Adicionar Ficheiro";

?>

<?php echo $this->renderPartial('_form', array('model'=>$model));

$this->endWidget();
?>


</div>
</div>

protected/views/ficheiro/index.php
<?php
$this->breadcrumbs=array(
	'Ficheiros',
);

$this->menu=array(
array('label'=>'Create Ficheiro','url'=>array('create')),
array('label'=>'Manage Ficheiro','url'=>array('admin')),
);
?>

<h1>Ficheiros</h1>

<?php $this->widget('bootstrap.widgets.TbListView',array(
'dataProvider'=>$dataProvider,
'itemView'=>'_view',
)); ?>

protected/views/ficheiro/update.php
<div class="row-fluid">
    <div class="span12">

<?php
    $this->beginWidget('bootstrap.widgets.TbBox', array(
    'title' => 'Editar Ficheiro '.$model->titulo_pt,
    'headerIcon' => 'icon-file',
    'headerButtons' => array(
   
    array(
    'class' => 'bootstrap.widgets.TbButtonGroup',
    'buttons'=>array(
    array('label'=>'Gerir Ficheiros', 'url'=>Yii::app()->baseUrl.'/ficheiro/admin'),
    ),
    ),
    )));

$this->pageTitle=Yii::app()->name.' - '."Editar Ficheiro ".$model->titulo_pt;

?>

<?php echo $this->renderPartial('_form', array('model'=>$model));

$this->endWidget();
?>


</div>
</div>

protected/views/ficheiro/view.php
<?php
$this->breadcrumbs=array(
	'Ficheiros'=>array('index'),
	$model->id,
);

$this->menu=array(
array('label'=>'List Ficheiro','url'=>array('index')),
array('label'=>'Create Ficheiro','url'=>array('create')),
array('label'=>'Update Ficheiro','url'=>array('update','id'=>$model->id)),
array('label'=>'Delete Ficheiro','url'=>'#','linkOptions'=>array('submit'=>array('delete','id'=>$model->id),'confirm'=>'Are you sure you want to delete this item?')),
array('label'=>'Manage Ficheiro','url'=>array('admin')),
);
?>

<h1>View Ficheiro #<?php echo $model->id; ?></h1>

<?php $this->widget('bootstrap.widgets.TbDetailView',array(
'data'=>$model,
'attributes'=>array(
		'id',
		'src',
),
)); ?>